# Simplified XGBoost for when you have many features but limited data

backend: xgboost
label_col: y_moved

model:
  type: XGBClassifier

  params:
    # Simpler trees
    booster: gbtree
    max_depth: 7              # Shallower trees
    min_child_weight: 9      # More conservative splits

    # Stronger regularization
    reg_alpha: 4.66e-06       # L1 (feature selection)
    reg_lambda: 2.5e-08      # L2 (prevent overfitting)
    gamma: 1.24               # Minimum loss reduction

    # More aggressive sampling (reduce overfitting)
    subsample: 0.61
    colsample_bytree: 0.6385     # Use only 50% of features per tree
    colsample_bylevel: 0.6

    # Learning
    learning_rate: 0.0233
    n_estimators: 850         # Fewer trees
    early_stopping_rounds: 20

    # Class imbalance
    scale_pos_weight: 15
    max_delta_step: 1

    # Hardware
    tree_method: hist
    device: cuda
    objective: binary:logistic
    eval_metric: aucpr

    # Reproducibility
    seed: 42
    random_state: 42
    verbose_eval: 10
